/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) deepc_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {20, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {915, 1, 1};
static const casadi_int casadi_s3[3] = {15, 1, 1};

/* deepc_constr_h_fun:(i0[20],i1[0],i2[0],i3[915])->(o0[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22;
  a00=arg[3]? arg[3][15] : 0;
  a01=arg[0]? arg[0][0] : 0;
  a00=(a00*a01);
  a02=arg[3]? arg[3][20] : 0;
  a03=arg[0]? arg[0][1] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[3]? arg[3][25] : 0;
  a04=arg[0]? arg[0][2] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[3]? arg[3][30] : 0;
  a05=arg[0]? arg[0][3] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[3]? arg[3][35] : 0;
  a06=arg[0]? arg[0][4] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[3]? arg[3][40] : 0;
  a07=arg[0]? arg[0][5] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[3]? arg[3][45] : 0;
  a08=arg[0]? arg[0][6] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[3]? arg[3][50] : 0;
  a09=arg[0]? arg[0][7] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[3]? arg[3][55] : 0;
  a10=arg[0]? arg[0][8] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[3]? arg[3][60] : 0;
  a11=arg[0]? arg[0][9] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[3]? arg[3][65] : 0;
  a12=arg[0]? arg[0][10] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[3]? arg[3][70] : 0;
  a13=arg[0]? arg[0][11] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[3]? arg[3][75] : 0;
  a14=arg[0]? arg[0][12] : 0;
  a02=(a02*a14);
  a00=(a00+a02);
  a02=arg[3]? arg[3][80] : 0;
  a15=arg[0]? arg[0][13] : 0;
  a02=(a02*a15);
  a00=(a00+a02);
  a02=arg[3]? arg[3][85] : 0;
  a16=arg[0]? arg[0][14] : 0;
  a02=(a02*a16);
  a00=(a00+a02);
  a02=arg[3]? arg[3][90] : 0;
  a17=arg[0]? arg[0][15] : 0;
  a02=(a02*a17);
  a00=(a00+a02);
  a02=arg[3]? arg[3][95] : 0;
  a18=arg[0]? arg[0][16] : 0;
  a02=(a02*a18);
  a00=(a00+a02);
  a02=arg[3]? arg[3][100] : 0;
  a19=arg[0]? arg[0][17] : 0;
  a02=(a02*a19);
  a00=(a00+a02);
  a02=arg[3]? arg[3][105] : 0;
  a20=arg[0]? arg[0][18] : 0;
  a02=(a02*a20);
  a00=(a00+a02);
  a02=arg[3]? arg[3][110] : 0;
  a21=arg[0]? arg[0][19] : 0;
  a02=(a02*a21);
  a00=(a00+a02);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[3]? arg[3][16] : 0;
  a00=(a00*a01);
  a02=arg[3]? arg[3][21] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[3]? arg[3][26] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[3]? arg[3][31] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[3]? arg[3][36] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[3]? arg[3][41] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[3]? arg[3][46] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[3]? arg[3][51] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[3]? arg[3][56] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[3]? arg[3][61] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[3]? arg[3][66] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[3]? arg[3][71] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[3]? arg[3][76] : 0;
  a02=(a02*a14);
  a00=(a00+a02);
  a02=arg[3]? arg[3][81] : 0;
  a02=(a02*a15);
  a00=(a00+a02);
  a02=arg[3]? arg[3][86] : 0;
  a02=(a02*a16);
  a00=(a00+a02);
  a02=arg[3]? arg[3][91] : 0;
  a02=(a02*a17);
  a00=(a00+a02);
  a02=arg[3]? arg[3][96] : 0;
  a02=(a02*a18);
  a00=(a00+a02);
  a02=arg[3]? arg[3][101] : 0;
  a02=(a02*a19);
  a00=(a00+a02);
  a02=arg[3]? arg[3][106] : 0;
  a02=(a02*a20);
  a00=(a00+a02);
  a02=arg[3]? arg[3][111] : 0;
  a02=(a02*a21);
  a00=(a00+a02);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[3]? arg[3][17] : 0;
  a00=(a00*a01);
  a02=arg[3]? arg[3][22] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[3]? arg[3][27] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[3]? arg[3][32] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[3]? arg[3][37] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[3]? arg[3][42] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[3]? arg[3][47] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[3]? arg[3][52] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[3]? arg[3][57] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[3]? arg[3][62] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[3]? arg[3][67] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[3]? arg[3][72] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[3]? arg[3][77] : 0;
  a02=(a02*a14);
  a00=(a00+a02);
  a02=arg[3]? arg[3][82] : 0;
  a02=(a02*a15);
  a00=(a00+a02);
  a02=arg[3]? arg[3][87] : 0;
  a02=(a02*a16);
  a00=(a00+a02);
  a02=arg[3]? arg[3][92] : 0;
  a02=(a02*a17);
  a00=(a00+a02);
  a02=arg[3]? arg[3][97] : 0;
  a02=(a02*a18);
  a00=(a00+a02);
  a02=arg[3]? arg[3][102] : 0;
  a02=(a02*a19);
  a00=(a00+a02);
  a02=arg[3]? arg[3][107] : 0;
  a02=(a02*a20);
  a00=(a00+a02);
  a02=arg[3]? arg[3][112] : 0;
  a02=(a02*a21);
  a00=(a00+a02);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[3]? arg[3][18] : 0;
  a00=(a00*a01);
  a02=arg[3]? arg[3][23] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[3]? arg[3][28] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[3]? arg[3][33] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[3]? arg[3][38] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[3]? arg[3][43] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[3]? arg[3][48] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[3]? arg[3][53] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[3]? arg[3][58] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[3]? arg[3][63] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[3]? arg[3][68] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[3]? arg[3][73] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[3]? arg[3][78] : 0;
  a02=(a02*a14);
  a00=(a00+a02);
  a02=arg[3]? arg[3][83] : 0;
  a02=(a02*a15);
  a00=(a00+a02);
  a02=arg[3]? arg[3][88] : 0;
  a02=(a02*a16);
  a00=(a00+a02);
  a02=arg[3]? arg[3][93] : 0;
  a02=(a02*a17);
  a00=(a00+a02);
  a02=arg[3]? arg[3][98] : 0;
  a02=(a02*a18);
  a00=(a00+a02);
  a02=arg[3]? arg[3][103] : 0;
  a02=(a02*a19);
  a00=(a00+a02);
  a02=arg[3]? arg[3][108] : 0;
  a02=(a02*a20);
  a00=(a00+a02);
  a02=arg[3]? arg[3][113] : 0;
  a02=(a02*a21);
  a00=(a00+a02);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[3]? arg[3][19] : 0;
  a00=(a00*a01);
  a02=arg[3]? arg[3][24] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[3]? arg[3][29] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[3]? arg[3][34] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[3]? arg[3][39] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[3]? arg[3][44] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[3]? arg[3][49] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[3]? arg[3][54] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[3]? arg[3][59] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[3]? arg[3][64] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[3]? arg[3][69] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[3]? arg[3][74] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[3]? arg[3][79] : 0;
  a02=(a02*a14);
  a00=(a00+a02);
  a02=arg[3]? arg[3][84] : 0;
  a02=(a02*a15);
  a00=(a00+a02);
  a02=arg[3]? arg[3][89] : 0;
  a02=(a02*a16);
  a00=(a00+a02);
  a02=arg[3]? arg[3][94] : 0;
  a02=(a02*a17);
  a00=(a00+a02);
  a02=arg[3]? arg[3][99] : 0;
  a02=(a02*a18);
  a00=(a00+a02);
  a02=arg[3]? arg[3][104] : 0;
  a02=(a02*a19);
  a00=(a00+a02);
  a02=arg[3]? arg[3][109] : 0;
  a02=(a02*a20);
  a00=(a00+a02);
  a02=arg[3]? arg[3][114] : 0;
  a02=(a02*a21);
  a00=(a00+a02);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[3]? arg[3][115] : 0;
  a00=(a00*a01);
  a02=arg[3]? arg[3][120] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[3]? arg[3][125] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[3]? arg[3][130] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[3]? arg[3][135] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[3]? arg[3][140] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[3]? arg[3][145] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[3]? arg[3][150] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[3]? arg[3][155] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[3]? arg[3][160] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[3]? arg[3][165] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[3]? arg[3][170] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[3]? arg[3][175] : 0;
  a02=(a02*a14);
  a00=(a00+a02);
  a02=arg[3]? arg[3][180] : 0;
  a02=(a02*a15);
  a00=(a00+a02);
  a02=arg[3]? arg[3][185] : 0;
  a02=(a02*a16);
  a00=(a00+a02);
  a02=arg[3]? arg[3][190] : 0;
  a02=(a02*a17);
  a00=(a00+a02);
  a02=arg[3]? arg[3][195] : 0;
  a02=(a02*a18);
  a00=(a00+a02);
  a02=arg[3]? arg[3][200] : 0;
  a02=(a02*a19);
  a00=(a00+a02);
  a02=arg[3]? arg[3][205] : 0;
  a02=(a02*a20);
  a00=(a00+a02);
  a02=arg[3]? arg[3][210] : 0;
  a02=(a02*a21);
  a00=(a00+a02);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[3]? arg[3][116] : 0;
  a00=(a00*a01);
  a02=arg[3]? arg[3][121] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[3]? arg[3][126] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[3]? arg[3][131] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[3]? arg[3][136] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[3]? arg[3][141] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[3]? arg[3][146] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[3]? arg[3][151] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[3]? arg[3][156] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[3]? arg[3][161] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[3]? arg[3][166] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[3]? arg[3][171] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[3]? arg[3][176] : 0;
  a02=(a02*a14);
  a00=(a00+a02);
  a02=arg[3]? arg[3][181] : 0;
  a02=(a02*a15);
  a00=(a00+a02);
  a02=arg[3]? arg[3][186] : 0;
  a02=(a02*a16);
  a00=(a00+a02);
  a02=arg[3]? arg[3][191] : 0;
  a02=(a02*a17);
  a00=(a00+a02);
  a02=arg[3]? arg[3][196] : 0;
  a02=(a02*a18);
  a00=(a00+a02);
  a02=arg[3]? arg[3][201] : 0;
  a02=(a02*a19);
  a00=(a00+a02);
  a02=arg[3]? arg[3][206] : 0;
  a02=(a02*a20);
  a00=(a00+a02);
  a02=arg[3]? arg[3][211] : 0;
  a02=(a02*a21);
  a00=(a00+a02);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[3]? arg[3][117] : 0;
  a00=(a00*a01);
  a02=arg[3]? arg[3][122] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[3]? arg[3][127] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[3]? arg[3][132] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[3]? arg[3][137] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[3]? arg[3][142] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[3]? arg[3][147] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[3]? arg[3][152] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[3]? arg[3][157] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[3]? arg[3][162] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[3]? arg[3][167] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[3]? arg[3][172] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[3]? arg[3][177] : 0;
  a02=(a02*a14);
  a00=(a00+a02);
  a02=arg[3]? arg[3][182] : 0;
  a02=(a02*a15);
  a00=(a00+a02);
  a02=arg[3]? arg[3][187] : 0;
  a02=(a02*a16);
  a00=(a00+a02);
  a02=arg[3]? arg[3][192] : 0;
  a02=(a02*a17);
  a00=(a00+a02);
  a02=arg[3]? arg[3][197] : 0;
  a02=(a02*a18);
  a00=(a00+a02);
  a02=arg[3]? arg[3][202] : 0;
  a02=(a02*a19);
  a00=(a00+a02);
  a02=arg[3]? arg[3][207] : 0;
  a02=(a02*a20);
  a00=(a00+a02);
  a02=arg[3]? arg[3][212] : 0;
  a02=(a02*a21);
  a00=(a00+a02);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[3]? arg[3][118] : 0;
  a00=(a00*a01);
  a02=arg[3]? arg[3][123] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[3]? arg[3][128] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[3]? arg[3][133] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[3]? arg[3][138] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[3]? arg[3][143] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[3]? arg[3][148] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[3]? arg[3][153] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[3]? arg[3][158] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[3]? arg[3][163] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[3]? arg[3][168] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[3]? arg[3][173] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[3]? arg[3][178] : 0;
  a02=(a02*a14);
  a00=(a00+a02);
  a02=arg[3]? arg[3][183] : 0;
  a02=(a02*a15);
  a00=(a00+a02);
  a02=arg[3]? arg[3][188] : 0;
  a02=(a02*a16);
  a00=(a00+a02);
  a02=arg[3]? arg[3][193] : 0;
  a02=(a02*a17);
  a00=(a00+a02);
  a02=arg[3]? arg[3][198] : 0;
  a02=(a02*a18);
  a00=(a00+a02);
  a02=arg[3]? arg[3][203] : 0;
  a02=(a02*a19);
  a00=(a00+a02);
  a02=arg[3]? arg[3][208] : 0;
  a02=(a02*a20);
  a00=(a00+a02);
  a02=arg[3]? arg[3][213] : 0;
  a02=(a02*a21);
  a00=(a00+a02);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[3]? arg[3][119] : 0;
  a00=(a00*a01);
  a02=arg[3]? arg[3][124] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[3]? arg[3][129] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[3]? arg[3][134] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[3]? arg[3][139] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[3]? arg[3][144] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[3]? arg[3][149] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[3]? arg[3][154] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[3]? arg[3][159] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[3]? arg[3][164] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[3]? arg[3][169] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[3]? arg[3][174] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[3]? arg[3][179] : 0;
  a02=(a02*a14);
  a00=(a00+a02);
  a02=arg[3]? arg[3][184] : 0;
  a02=(a02*a15);
  a00=(a00+a02);
  a02=arg[3]? arg[3][189] : 0;
  a02=(a02*a16);
  a00=(a00+a02);
  a02=arg[3]? arg[3][194] : 0;
  a02=(a02*a17);
  a00=(a00+a02);
  a02=arg[3]? arg[3][199] : 0;
  a02=(a02*a18);
  a00=(a00+a02);
  a02=arg[3]? arg[3][204] : 0;
  a02=(a02*a19);
  a00=(a00+a02);
  a02=arg[3]? arg[3][209] : 0;
  a02=(a02*a20);
  a00=(a00+a02);
  a02=arg[3]? arg[3][214] : 0;
  a02=(a02*a21);
  a00=(a00+a02);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[3]? arg[3][215] : 0;
  a00=(a00*a01);
  a02=arg[3]? arg[3][220] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[3]? arg[3][225] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[3]? arg[3][230] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[3]? arg[3][235] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[3]? arg[3][240] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[3]? arg[3][245] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[3]? arg[3][250] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[3]? arg[3][255] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[3]? arg[3][260] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[3]? arg[3][265] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[3]? arg[3][270] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[3]? arg[3][275] : 0;
  a02=(a02*a14);
  a00=(a00+a02);
  a02=arg[3]? arg[3][280] : 0;
  a02=(a02*a15);
  a00=(a00+a02);
  a02=arg[3]? arg[3][285] : 0;
  a02=(a02*a16);
  a00=(a00+a02);
  a02=arg[3]? arg[3][290] : 0;
  a02=(a02*a17);
  a00=(a00+a02);
  a02=arg[3]? arg[3][295] : 0;
  a02=(a02*a18);
  a00=(a00+a02);
  a02=arg[3]? arg[3][300] : 0;
  a02=(a02*a19);
  a00=(a00+a02);
  a02=arg[3]? arg[3][305] : 0;
  a02=(a02*a20);
  a00=(a00+a02);
  a02=arg[3]? arg[3][310] : 0;
  a02=(a02*a21);
  a00=(a00+a02);
  a02=arg[3]? arg[3][4] : 0;
  a02=(a00-a02);
  if (res[0]!=0) res[0][10]=a02;
  a02=arg[3]? arg[3][216] : 0;
  a02=(a02*a01);
  a22=arg[3]? arg[3][221] : 0;
  a22=(a22*a03);
  a02=(a02+a22);
  a22=arg[3]? arg[3][226] : 0;
  a22=(a22*a04);
  a02=(a02+a22);
  a22=arg[3]? arg[3][231] : 0;
  a22=(a22*a05);
  a02=(a02+a22);
  a22=arg[3]? arg[3][236] : 0;
  a22=(a22*a06);
  a02=(a02+a22);
  a22=arg[3]? arg[3][241] : 0;
  a22=(a22*a07);
  a02=(a02+a22);
  a22=arg[3]? arg[3][246] : 0;
  a22=(a22*a08);
  a02=(a02+a22);
  a22=arg[3]? arg[3][251] : 0;
  a22=(a22*a09);
  a02=(a02+a22);
  a22=arg[3]? arg[3][256] : 0;
  a22=(a22*a10);
  a02=(a02+a22);
  a22=arg[3]? arg[3][261] : 0;
  a22=(a22*a11);
  a02=(a02+a22);
  a22=arg[3]? arg[3][266] : 0;
  a22=(a22*a12);
  a02=(a02+a22);
  a22=arg[3]? arg[3][271] : 0;
  a22=(a22*a13);
  a02=(a02+a22);
  a22=arg[3]? arg[3][276] : 0;
  a22=(a22*a14);
  a02=(a02+a22);
  a22=arg[3]? arg[3][281] : 0;
  a22=(a22*a15);
  a02=(a02+a22);
  a22=arg[3]? arg[3][286] : 0;
  a22=(a22*a16);
  a02=(a02+a22);
  a22=arg[3]? arg[3][291] : 0;
  a22=(a22*a17);
  a02=(a02+a22);
  a22=arg[3]? arg[3][296] : 0;
  a22=(a22*a18);
  a02=(a02+a22);
  a22=arg[3]? arg[3][301] : 0;
  a22=(a22*a19);
  a02=(a02+a22);
  a22=arg[3]? arg[3][306] : 0;
  a22=(a22*a20);
  a02=(a02+a22);
  a22=arg[3]? arg[3][311] : 0;
  a22=(a22*a21);
  a02=(a02+a22);
  a00=(a02-a00);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[3]? arg[3][217] : 0;
  a00=(a00*a01);
  a22=arg[3]? arg[3][222] : 0;
  a22=(a22*a03);
  a00=(a00+a22);
  a22=arg[3]? arg[3][227] : 0;
  a22=(a22*a04);
  a00=(a00+a22);
  a22=arg[3]? arg[3][232] : 0;
  a22=(a22*a05);
  a00=(a00+a22);
  a22=arg[3]? arg[3][237] : 0;
  a22=(a22*a06);
  a00=(a00+a22);
  a22=arg[3]? arg[3][242] : 0;
  a22=(a22*a07);
  a00=(a00+a22);
  a22=arg[3]? arg[3][247] : 0;
  a22=(a22*a08);
  a00=(a00+a22);
  a22=arg[3]? arg[3][252] : 0;
  a22=(a22*a09);
  a00=(a00+a22);
  a22=arg[3]? arg[3][257] : 0;
  a22=(a22*a10);
  a00=(a00+a22);
  a22=arg[3]? arg[3][262] : 0;
  a22=(a22*a11);
  a00=(a00+a22);
  a22=arg[3]? arg[3][267] : 0;
  a22=(a22*a12);
  a00=(a00+a22);
  a22=arg[3]? arg[3][272] : 0;
  a22=(a22*a13);
  a00=(a00+a22);
  a22=arg[3]? arg[3][277] : 0;
  a22=(a22*a14);
  a00=(a00+a22);
  a22=arg[3]? arg[3][282] : 0;
  a22=(a22*a15);
  a00=(a00+a22);
  a22=arg[3]? arg[3][287] : 0;
  a22=(a22*a16);
  a00=(a00+a22);
  a22=arg[3]? arg[3][292] : 0;
  a22=(a22*a17);
  a00=(a00+a22);
  a22=arg[3]? arg[3][297] : 0;
  a22=(a22*a18);
  a00=(a00+a22);
  a22=arg[3]? arg[3][302] : 0;
  a22=(a22*a19);
  a00=(a00+a22);
  a22=arg[3]? arg[3][307] : 0;
  a22=(a22*a20);
  a00=(a00+a22);
  a22=arg[3]? arg[3][312] : 0;
  a22=(a22*a21);
  a00=(a00+a22);
  a02=(a00-a02);
  if (res[0]!=0) res[0][12]=a02;
  a02=arg[3]? arg[3][218] : 0;
  a02=(a02*a01);
  a22=arg[3]? arg[3][223] : 0;
  a22=(a22*a03);
  a02=(a02+a22);
  a22=arg[3]? arg[3][228] : 0;
  a22=(a22*a04);
  a02=(a02+a22);
  a22=arg[3]? arg[3][233] : 0;
  a22=(a22*a05);
  a02=(a02+a22);
  a22=arg[3]? arg[3][238] : 0;
  a22=(a22*a06);
  a02=(a02+a22);
  a22=arg[3]? arg[3][243] : 0;
  a22=(a22*a07);
  a02=(a02+a22);
  a22=arg[3]? arg[3][248] : 0;
  a22=(a22*a08);
  a02=(a02+a22);
  a22=arg[3]? arg[3][253] : 0;
  a22=(a22*a09);
  a02=(a02+a22);
  a22=arg[3]? arg[3][258] : 0;
  a22=(a22*a10);
  a02=(a02+a22);
  a22=arg[3]? arg[3][263] : 0;
  a22=(a22*a11);
  a02=(a02+a22);
  a22=arg[3]? arg[3][268] : 0;
  a22=(a22*a12);
  a02=(a02+a22);
  a22=arg[3]? arg[3][273] : 0;
  a22=(a22*a13);
  a02=(a02+a22);
  a22=arg[3]? arg[3][278] : 0;
  a22=(a22*a14);
  a02=(a02+a22);
  a22=arg[3]? arg[3][283] : 0;
  a22=(a22*a15);
  a02=(a02+a22);
  a22=arg[3]? arg[3][288] : 0;
  a22=(a22*a16);
  a02=(a02+a22);
  a22=arg[3]? arg[3][293] : 0;
  a22=(a22*a17);
  a02=(a02+a22);
  a22=arg[3]? arg[3][298] : 0;
  a22=(a22*a18);
  a02=(a02+a22);
  a22=arg[3]? arg[3][303] : 0;
  a22=(a22*a19);
  a02=(a02+a22);
  a22=arg[3]? arg[3][308] : 0;
  a22=(a22*a20);
  a02=(a02+a22);
  a22=arg[3]? arg[3][313] : 0;
  a22=(a22*a21);
  a02=(a02+a22);
  a00=(a02-a00);
  if (res[0]!=0) res[0][13]=a00;
  a00=arg[3]? arg[3][219] : 0;
  a00=(a00*a01);
  a01=arg[3]? arg[3][224] : 0;
  a01=(a01*a03);
  a00=(a00+a01);
  a01=arg[3]? arg[3][229] : 0;
  a01=(a01*a04);
  a00=(a00+a01);
  a01=arg[3]? arg[3][234] : 0;
  a01=(a01*a05);
  a00=(a00+a01);
  a01=arg[3]? arg[3][239] : 0;
  a01=(a01*a06);
  a00=(a00+a01);
  a01=arg[3]? arg[3][244] : 0;
  a01=(a01*a07);
  a00=(a00+a01);
  a01=arg[3]? arg[3][249] : 0;
  a01=(a01*a08);
  a00=(a00+a01);
  a01=arg[3]? arg[3][254] : 0;
  a01=(a01*a09);
  a00=(a00+a01);
  a01=arg[3]? arg[3][259] : 0;
  a01=(a01*a10);
  a00=(a00+a01);
  a01=arg[3]? arg[3][264] : 0;
  a01=(a01*a11);
  a00=(a00+a01);
  a01=arg[3]? arg[3][269] : 0;
  a01=(a01*a12);
  a00=(a00+a01);
  a01=arg[3]? arg[3][274] : 0;
  a01=(a01*a13);
  a00=(a00+a01);
  a01=arg[3]? arg[3][279] : 0;
  a01=(a01*a14);
  a00=(a00+a01);
  a01=arg[3]? arg[3][284] : 0;
  a01=(a01*a15);
  a00=(a00+a01);
  a01=arg[3]? arg[3][289] : 0;
  a01=(a01*a16);
  a00=(a00+a01);
  a01=arg[3]? arg[3][294] : 0;
  a01=(a01*a17);
  a00=(a00+a01);
  a01=arg[3]? arg[3][299] : 0;
  a01=(a01*a18);
  a00=(a00+a01);
  a01=arg[3]? arg[3][304] : 0;
  a01=(a01*a19);
  a00=(a00+a01);
  a01=arg[3]? arg[3][309] : 0;
  a01=(a01*a20);
  a00=(a00+a01);
  a01=arg[3]? arg[3][314] : 0;
  a01=(a01*a21);
  a00=(a00+a01);
  a00=(a00-a02);
  if (res[0]!=0) res[0][14]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int deepc_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int deepc_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int deepc_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void deepc_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int deepc_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void deepc_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void deepc_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void deepc_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int deepc_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int deepc_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real deepc_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* deepc_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* deepc_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* deepc_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* deepc_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int deepc_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int deepc_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
