/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) deepc_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {106, 1, 1};
static const casadi_int casadi_s3[3] = {6, 6, 1};
static const casadi_int casadi_s4[3] = {6, 0, 1};

/* deepc_constr_h_fun_jac_uxt_zt:(i0[6],i1[0],i2[0],i3[106])->(o0[6],o1[6x6],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38;
  a00=arg[3]? arg[3][6] : 0;
  a01=arg[0]? arg[0][0] : 0;
  a02=(a00*a01);
  a03=arg[3]? arg[3][8] : 0;
  a04=arg[0]? arg[0][1] : 0;
  a05=(a03*a04);
  a02=(a02+a05);
  a05=arg[3]? arg[3][10] : 0;
  a06=arg[0]? arg[0][2] : 0;
  a07=(a05*a06);
  a02=(a02+a07);
  a07=arg[3]? arg[3][12] : 0;
  a08=arg[0]? arg[0][3] : 0;
  a09=(a07*a08);
  a02=(a02+a09);
  a09=arg[3]? arg[3][14] : 0;
  a10=arg[0]? arg[0][4] : 0;
  a11=(a09*a10);
  a02=(a02+a11);
  a11=arg[3]? arg[3][16] : 0;
  a12=arg[0]? arg[0][5] : 0;
  a13=(a11*a12);
  a02=(a02+a13);
  if (res[0]!=0) res[0][0]=a02;
  a02=arg[3]? arg[3][7] : 0;
  a13=(a02*a01);
  a14=arg[3]? arg[3][9] : 0;
  a15=(a14*a04);
  a13=(a13+a15);
  a15=arg[3]? arg[3][11] : 0;
  a16=(a15*a06);
  a13=(a13+a16);
  a16=arg[3]? arg[3][13] : 0;
  a17=(a16*a08);
  a13=(a13+a17);
  a17=arg[3]? arg[3][15] : 0;
  a18=(a17*a10);
  a13=(a13+a18);
  a18=arg[3]? arg[3][17] : 0;
  a19=(a18*a12);
  a13=(a13+a19);
  if (res[0]!=0) res[0][1]=a13;
  a13=arg[3]? arg[3][18] : 0;
  a19=(a13*a01);
  a20=arg[3]? arg[3][20] : 0;
  a21=(a20*a04);
  a19=(a19+a21);
  a21=arg[3]? arg[3][22] : 0;
  a22=(a21*a06);
  a19=(a19+a22);
  a22=arg[3]? arg[3][24] : 0;
  a23=(a22*a08);
  a19=(a19+a23);
  a23=arg[3]? arg[3][26] : 0;
  a24=(a23*a10);
  a19=(a19+a24);
  a24=arg[3]? arg[3][28] : 0;
  a25=(a24*a12);
  a19=(a19+a25);
  if (res[0]!=0) res[0][2]=a19;
  a19=arg[3]? arg[3][19] : 0;
  a25=(a19*a01);
  a26=arg[3]? arg[3][21] : 0;
  a27=(a26*a04);
  a25=(a25+a27);
  a27=arg[3]? arg[3][23] : 0;
  a28=(a27*a06);
  a25=(a25+a28);
  a28=arg[3]? arg[3][25] : 0;
  a29=(a28*a08);
  a25=(a25+a29);
  a29=arg[3]? arg[3][27] : 0;
  a30=(a29*a10);
  a25=(a25+a30);
  a30=arg[3]? arg[3][29] : 0;
  a31=(a30*a12);
  a25=(a25+a31);
  if (res[0]!=0) res[0][3]=a25;
  a25=arg[3]? arg[3][30] : 0;
  a31=(a25*a01);
  a32=arg[3]? arg[3][32] : 0;
  a33=(a32*a04);
  a31=(a31+a33);
  a33=arg[3]? arg[3][34] : 0;
  a34=(a33*a06);
  a31=(a31+a34);
  a34=arg[3]? arg[3][36] : 0;
  a35=(a34*a08);
  a31=(a31+a35);
  a35=arg[3]? arg[3][38] : 0;
  a36=(a35*a10);
  a31=(a31+a36);
  a36=arg[3]? arg[3][40] : 0;
  a37=(a36*a12);
  a31=(a31+a37);
  a37=arg[3]? arg[3][1] : 0;
  a37=(a31-a37);
  if (res[0]!=0) res[0][4]=a37;
  a37=arg[3]? arg[3][31] : 0;
  a01=(a37*a01);
  a38=arg[3]? arg[3][33] : 0;
  a04=(a38*a04);
  a01=(a01+a04);
  a04=arg[3]? arg[3][35] : 0;
  a06=(a04*a06);
  a01=(a01+a06);
  a06=arg[3]? arg[3][37] : 0;
  a08=(a06*a08);
  a01=(a01+a08);
  a08=arg[3]? arg[3][39] : 0;
  a10=(a08*a10);
  a01=(a01+a10);
  a10=arg[3]? arg[3][41] : 0;
  a12=(a10*a12);
  a01=(a01+a12);
  a01=(a01-a31);
  if (res[0]!=0) res[0][5]=a01;
  if (res[1]!=0) res[1][0]=a00;
  if (res[1]!=0) res[1][1]=a03;
  if (res[1]!=0) res[1][2]=a05;
  if (res[1]!=0) res[1][3]=a07;
  if (res[1]!=0) res[1][4]=a09;
  if (res[1]!=0) res[1][5]=a11;
  if (res[1]!=0) res[1][6]=a02;
  if (res[1]!=0) res[1][7]=a14;
  if (res[1]!=0) res[1][8]=a15;
  if (res[1]!=0) res[1][9]=a16;
  if (res[1]!=0) res[1][10]=a17;
  if (res[1]!=0) res[1][11]=a18;
  if (res[1]!=0) res[1][12]=a13;
  if (res[1]!=0) res[1][13]=a20;
  if (res[1]!=0) res[1][14]=a21;
  if (res[1]!=0) res[1][15]=a22;
  if (res[1]!=0) res[1][16]=a23;
  if (res[1]!=0) res[1][17]=a24;
  if (res[1]!=0) res[1][18]=a19;
  if (res[1]!=0) res[1][19]=a26;
  if (res[1]!=0) res[1][20]=a27;
  if (res[1]!=0) res[1][21]=a28;
  if (res[1]!=0) res[1][22]=a29;
  if (res[1]!=0) res[1][23]=a30;
  if (res[1]!=0) res[1][24]=a25;
  if (res[1]!=0) res[1][25]=a32;
  if (res[1]!=0) res[1][26]=a33;
  if (res[1]!=0) res[1][27]=a34;
  if (res[1]!=0) res[1][28]=a35;
  if (res[1]!=0) res[1][29]=a36;
  a37=(a37-a25);
  if (res[1]!=0) res[1][30]=a37;
  a38=(a38-a32);
  if (res[1]!=0) res[1][31]=a38;
  a04=(a04-a33);
  if (res[1]!=0) res[1][32]=a04;
  a06=(a06-a34);
  if (res[1]!=0) res[1][33]=a06;
  a08=(a08-a35);
  if (res[1]!=0) res[1][34]=a08;
  a10=(a10-a36);
  if (res[1]!=0) res[1][35]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int deepc_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int deepc_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int deepc_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void deepc_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int deepc_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void deepc_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void deepc_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void deepc_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int deepc_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int deepc_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real deepc_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* deepc_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* deepc_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* deepc_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* deepc_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int deepc_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int deepc_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
